main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

order/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('addtoshopcart/<int:id>', views.addtoshopcart, name='addtoshopcart'),
    path('shopcart/', views.shopcart, name='shopcart'),
    path('deletefromcart/<int:id>', views.deletefromcart, name='deletefromcart'),
    path('orderproduct/', views.orderproduct, name='orderproduct'),
    path('pay_success', views.pay_success, name='pay_success'),
    path('pay_cancel', views.pay_cancel, name='pay_cancel'),
    path('checkout_session/', views.checkout_session, name='checkout_session'),
    #path('pay_mob/', views.pay_mob, name='pay_mob'),
    #path('webhook/stripe', views.my_webhook_view, name='webhook-stripe'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('', include('main.urls')),
                  path('products/', include('products.urls')),
                  path('order/', include('order.urls')),
                  path('user/', include('user.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('change-password/', auth_views.PasswordChangeView.as_view()),
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm

from products.models import Product, Variants


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL,blank=True, null=True) # relation with varinat
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.name

    @property
    def price(self):
        return (self.product.default_price)

    @property
    def amount(self):
        return (self.quantity * self.product.default_price)

    @property
    def vamount(self):
        return (self.quantity * self.variant.price)


class ShopCartForm(ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity']

class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False,unique=True )
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    total = models.FloatField()
    status=models.CharField(max_length=10,choices=STATUS,default='New')
    adminnote = models.CharField(blank=True, max_length=100)
    create_at=models.DateTimeField(auto_now_add=True)
    update_at=models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    def __str__(self):
        return self.user.first_name

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'phone', 'city']

class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant = models.ForeignKey(Variants, on_delete=models.SET_NULL,blank=True, null=True) # relation with varinat
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name

order/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

order/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils.crypto import get_random_string
from django.shortcuts import render, get_object_or_404, redirect
from order.models import ShopCart, ShopCartForm, OrderForm, Order, OrderProduct
from products.models import Category, Product, Variants
from user.models import Profile
import stripe


stripe.api_key = 'sk_test_51M8qGSGrudnGZQOKK9zBQ5paV7j8sEy1lILyqbd9nj7aSuFSjSgo66Jqwbfn7eQT8QGXrhebyKbfASBJ1YRck1fH00kggt4emO'



def index(request):
    return HttpResponse ("Order Page")

@login_required(login_url='/login') # Check login
def addtoshopcart(request,id):
    url = request.META.get('HTTP_REFERER')  # get last url
    current_user = request.user  # Access User Session information
    product= Product.objects.get(pk=id)

    if product.variant != 'None':
        variantid = request.POST.get('variantid')  # from variant add to cart
        checkinvariant = ShopCart.objects.filter(variant_id=variantid, user_id=current_user.id)  # Check product in shopcart
        if checkinvariant:
            control = 1 # The product is in the cart
        else:
            control = 0 # The product is not in the cart"""
    else:
        checkinproduct = ShopCart.objects.filter(product_id=id, user_id=current_user.id) # Check product in shopcart
        if checkinproduct:
            control = 1 # The product is in the cart
        else:
            control = 0 # The product is not in the cart"""

    if request.method == 'POST':  # if there is a post
        form = ShopCartForm(request.POST)
        if form.is_valid():
            if control == 1 :  # Update  shopcart
                data = ShopCart.objects.get(product_id=id, variant_id=variantid, user_id=current_user.id)
                if str(data.variant.quantity) > str(data.quantity):
                    data.quantity += form.cleaned_data['quantity']
                    data.save()  # save data
                    messages.success(request, "Shop Cart Updated")
                else:
                    messages.success(request, "No More Products In Stock")

            else:  # Inser to Shopcart
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.variant_id = variantid
                data.quantity = form.cleaned_data['quantity']
                data.save()
                messages.success(request, "Product added to Shopcart ")
        return HttpResponseRedirect(url)

    else:  # if there is no post
        if control == 1 :  # Update  shopcart
            data = ShopCart.objects.get(variant_id=id, user_id=current_user.id)
            data.quantity += 1
            data.save()  #
        else:  # Inser to Shopcart
            data = ShopCart()  # model ile bağlantı kur
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.variant_id = None
            data.save()  #
        messages.success(request, "Shop Cart Updated")
        return HttpResponseRedirect(url)


def shopcart(request):
    category = Category.objects.all()
    current_user = request.user  # Access User Session information
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total=0
    for rs in shopcart:
        if rs.product.variant == 'None':
            total += rs.product.price * rs.quantity
        else:
            total += rs.variant.price * rs.quantity
    #return HttpResponse(str(total))
    context={'shopcart': shopcart,
             'category':category,
             'total': total,
             }
    return render(request, 'order/shopcart_products.html', context)

@login_required(login_url='/login') # Check login
def deletefromcart(request,id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, "Your item deleted form Shopcart.")
    return HttpResponseRedirect("/order/shopcart")


def orderproduct(request):
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for rs in shopcart:
        if rs.product.variant == 'None':
            total += rs.product.default_price * rs.quantity
        else:
            total += rs.variant.price * rs.quantity

    if request.method == 'POST':  # if there is a post
        form = OrderForm(request.POST)
        #return HttpResponse(request.POST.items())
        if form.is_valid():
            # Send Credit card to bank,  If the bank responds ok, continue, if not, show the error
            # ..............

            data = Order()
            data.first_name = form.cleaned_data['first_name'] #get product quantity from form
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            ordercode= get_random_string(5).upper() # random cod
            data.code =  ordercode
            data.save() #


            for rs in shopcart:
                detail = OrderProduct()
                detail.order_id     = data.id # Order Id
                detail.product_id   = rs.product_id
                detail.user_id      = current_user.id
                detail.quantity     = rs.quantity
                if rs.product.variant == 'None':
                    detail.price    = rs.product.price
                else:
                    detail.price = rs.variant.price
                detail.variant_id   = rs.variant_id
                detail.amount        = rs.amount
                detail.save()
                # ***Reduce quantity of sold product from Amount of Product
                if  rs.product.variant=='None':
                    product = Product.objects.get(id=rs.product_id)
                    product.amount -= rs.quantity
                    product.save()
                else:
                    variant = Variants.objects.get(id=rs.variant_id)
                    variant.quantity -= rs.quantity
                    variant.save()
                #************ <> *****************

            ShopCart.objects.filter(user_id=current_user.id).delete() # Clear & Delete shopcart
            request.session['cart_items']=0
            messages.success(request, "Your Order has been completed. Thank you ")
            return render(request, 'order/Order_Completed.html',{'ordercode':ordercode,'category': category})
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/order/orderproduct")

    form= OrderForm()
    profile = Profile.objects.get(user_id=current_user.id)
    context = {'shopcart': shopcart,
               'category': category,
               'total': total,
               'form': form,
               'profile': profile,
               }
    return render(request, 'order/Order_Form.html', context)



#########################Srtip############################


def checkout_session(request):
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for str in shopcart:
        total += str.variant.price * str.quantity
        session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[{
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                        'name': str.variant_id,
                    },
                    'unit_amount': int(total) * 100,
                },
                'quantity': 1,
            }],
            mode='payment',

            success_url='http://127.0.0.1:8000/order/pay_success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url='http://127.0.0.1:8000/pay_cancel',
        )
    return redirect(session.url, code=303)


def pay_success(request):
    current_user = request.user
    total = 0
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    for rs in shopcart:
        if rs.product.variant == 'None':
            total += rs.product.price * rs.quantity
        else:
            total += rs.variant.price * rs.quantity
    current_user = request.user
    #form = OrderForm(request.POST)
    data = Order()
    data.first_name = current_user.first_name # get product quantity from form
    data.last_name = current_user.last_name
    data.address = current_user.profile.address
    data.city = current_user.profile.city
    data.phone = current_user.profile.phone
    data.paid = True
    data.user_id = current_user.id
    data.total = total
    data.ip = request.META.get('REMOTE_ADDR')
    ordercode = get_random_string(5).upper()  # random cod
    data.code = ordercode
    data.save()  #

    for rs in shopcart:
        detail = OrderProduct()
        detail.order_id = data.id  # Order Id
        detail.product_id = rs.product_id
        detail.user_id = current_user.id
        detail.quantity = rs.quantity
        if rs.product.variant == 'None':
            detail.price = rs.product.price
        else:
            detail.price = rs.variant.price
        detail.variant_id = rs.variant_id
        detail.amount = rs.amount
        detail.save()
        # ***Reduce quantity of sold product from Amount of Product
        if rs.product.variant == 'None':
            product = Product.objects.get(id=rs.product_id)
            product.amount -= rs.quantity
            product.save()
        else:
            variant = Variants.objects.get(id=rs.variant_id)
            variant.quantity -= rs.quantity
            variant.save()


        # ************ <> *****************

    ShopCart.objects.filter(user_id=current_user.id).delete()  # Clear & Delete shopcart

templates/order/Order_Completed.html
{% extends 'base.html' %}



{% block content %}


<div class="card text-center">
  <div class="card-header">

  </div>
  <div class="card-body">

                        <hr>
                                                  {% if messages %}
                                        {% for message in messages %}
                                            <div class="alert alert-{{message.tags}}" role="alert">
                                                {{ message }}
                                            </div>
                                        {% endfor %}
                                    {% endif %}
                        <h2>Dear  {{ user.first_name }} {{  user.last_name }}</h2>
                        <hr>
                        <h3>Your order is completed</h3>
                        <h3>Trace Your Order Status : <a href="{% url 'user_index' %}">Your Profile</a></h3>
                        <h3>Thank You</h3>
                        <hr>
  </div>
  <div class="card-footer text-muted">
  </div>
</div>
      </div>
</div>

{% endblock %}

templates/order/Order_Form.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Samazon | Checkout {% endblock %}
{% block content %}



     <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Check Out</h4>
                        <div class="breadcrumb__links">
                            <a href="/">Home</a>
                            <a href="/products/">Shop</a>
                            <span>Check Out</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Checkout Section Begin -->
    <section class="checkout spad">
        <div class="container">
            <div class="checkout__form">
            {% if shopcart %}
                <form action="" method="post" >
                {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-8 col-md-6">
                            <h6 class="checkout__title">Billing Details</h6>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p for="id_first_name">Fist Name</p>
                                        <input name="first_name" type="text" value="{{ user.first_name }}" id="id_first_name">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p for="id_last_name">Last Name</p>
                                        <input name="last_name" type="text" value="{{ user.last_name }}" id="id_last_name">
                                    </div>
                                </div>
                            </div>
                            <div class="checkout__input">
                                <p for="id_address">Address</p>
                                <input name="address" type="text" placeholder="Street Address" class="checkout__input__add" value="{{ profile.address }}" id="id_address" >
                            </div>
                            <div class="checkout__input">
                                <p for="id_address">City</p>
                                <input name="city" type="text" value="{{ profile.city }}" id="id_city">
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="checkout__input">
                                        <p for="id_phone">Phone</p>
                                        <input name="phone" type="text" value="{{ profile.phone }}" id="id_phone" >
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                </div>
                            </div>

                        </div>
                        <div class="col-lg-4 col-md-6">
                            <div class="checkout__order">
                                <h4 class="order__title">Your order</h4>
                                <div class="checkout__order__products">Products <span>Total</span></div>

                                <ul class="checkout__total__products">
                                    {% for rs in shopcart %}
                                    <li>* {{rs.product.name}} ( {{ rs.variant.size }}  &  {{ rs.variant.color }} )
                                        {% if rs.product.variant == 'None' %}
                                        <span>{{ rs.total_price }}</span>
                                    {% else %}
                                    <span>{{ rs.vamount }}</span>
                                    {% endif %}
                                    </li>
                                    {% endfor %}
                                </ul>

                                <ul class="checkout__total__all">
                                    <li>Subtotal <span>{{ total }}</span></li>
                                    <li>Total <span>{{ total }}</span></li>
                                </ul>
                                


                                <button type="submit" class="site-btn">PLACE ORDER</button>

                            </div>
                        </div>
                    </div>

                </form>

                <form method="post" action="{% url 'checkout_session'  %}">
                    {% csrf_token %}
                    <input type="submit" value="Proceed to Online Payment" class="site-btn" />
                </form>
                
            {% else %}
                <h3 colspan="4" style="width:100%;text-align:center;">Your Cart Is Empty !</h3>
        {% endif %}
            </div>
        </div>
    </section>
    <!-- Checkout Section End -->

{% endblock %}

templates/order/shopcart_products.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{user.username}} | ShopCart {% endblock %}
{% block content %}

<!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shopping Cart</h4>
                        <div class="breadcrumb__links">
                            <a href="/">Home</a>
                            <a href="/products">Shop</a>
                            <span>Shopping Cart</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
<!-- Breadcrumb Section End -->

        <!-- Shopping Cart Section Begin -->
    <section class="shopping-cart spad">
        {% if request.user.is_authenticated %}
    {% if shopcart %}
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="shopping__cart__table">
                        <table>
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Quantity</th>
                                    <th>Total</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>

		                    {% for rs in shopcart %}
                                <tr>

                                    <td class="product__cart__item">
                                        <div class="product__cart__item__pic">
                                            {% if rs.variant.image_id  > 0 %}
                                            <img src="{{rs.variant.image }}" alt="" style="height: 50px; width: 60px ">
                                            {% else %}
                                            <img src="{{rs.product.image.url}}" alt="" style="height: 50px;width: 60px">
                                            {% endif %}
                                        </div>
                                        <div class="product__cart__item__text">
                                            <h6>{{rs.product.name}} ( {{ rs.variant.size }}  &  {{ rs.variant.color }} )</h6>

                                            {% if rs.product.variant == 'None' %}
                                            <h5>{{ rs.product.default_price }}</h5>
                                            {% else %}
                                                <h5>{{ rs.variant.price }}</h5>
                                            {% endif %}


                                        </div>
                                    </td>

                                    <td class="quantity__item">
                                        <div class="quantity">
                                            <div class="pro-qty-2">
                                                <input type="text" value={{rs.quantity}}>
                                            </div>
                                        </div>
                                    </td>

                                {% if rs.product.variant == 'None' %}
                                    <td class="cart__price">{{ rs.total_price }}</td>
                                {% else %}
                                    <td class="cart__price">{{ rs.vamount }}</td>
                                {% endif %}

                                    <td class="text-right"><a href="/order/deletefromcart/{{ rs.id }}" onclick="return confirm('Delete ! Are you sure?')" class="cart__close"><i class="fa fa-close"></i></a></td>


                                </tr>
                        {% endfor %}

                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn">
                                <a href="{% url 'products' %}">Continue Shopping</a>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn update__btn">
                                <a href="#"><i class="fa fa-spinner"></i> Update cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart__discount">
                        <h6>Discount codes</h6>
                        <form action="#">
                            <input type="text" placeholder="Coupon code">
                            <button type="submit">Apply</button>
                        </form>
                    </div>
                    <div class="cart__total">
                        <h6>Cart total</h6>
                        <ul>
                            <li>Subtotal <span>{{ total }}</span></li>
                            <li>Total <span>{{ total }}</span></li>
                        </ul>
                        <a href="{% url 'orderproduct' %}" class="primary-btn">Proceed to checkout</a>
                    </div>

                </div>
            </div>
        </div>
               {% else %}
				<h3 colspan="4" style="width:100%;text-align:center;">there is no product !</h3>
			{% endif %}
            {% else %}
            <h3 colspan="4" style="width:100%;text-align:center;"><a href="{% url 'login' %}">You Have To Login First !</a> </h3>
            {% endif %}

    </section>


    <!-- Shopping Cart Section End -->






{% endblock %}